app: aws-python-rest-api
service: aws-python-rest-api

provider:
  name: aws
  region: eu-west-2
  runtime: python3.7

functions:
  scorer:
    handler: handler.score
    events:
      - http:
          path: /score
          method: post
    layers:
      - arn:aws:lambda:eu-west-2:770693421928:layer:Klayers-python38-pandas:17
      - arn:aws:lambda:eu-west-2:770693421928:layer:Klayers-python38-numpy:10
            
  status:
    handler: handler.status
    events:
      - http:
          path: /
          method: get
    layers:
      - arn:aws:lambda:eu-west-2:770693421928:layer:Klayers-python38-pandas:17
      - arn:aws:lambda:eu-west-2:770693421928:layer:Klayers-python38-numpy:10
          

plugins:
  - serverless-python-requirements

  
custom:
  pythonRequirements:
    dockerizePip: 'non-linux'
    slim: true
    noDeploy:
      - six
      - threadpoolctl
      - jmespath
      - joblib
      - dateutil
      - numpy
  


